[features]
seeds = false
skip-lint = false
[programs.localnet]
intrant_inferis = "22GX4VQfqHoVNmL1LggYwZoMP8w5maRpyX7NCVTxyefh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
